services:
  - type: web
    name: lab-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: your-render-domain.onrender.com
      - key: DATABASE_URL
        value: your-database-url
