# Generated by Django 5.1.1 on 2025-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
