# Generated by Django 5.1.1 on 2025-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
