# Generated by Django 5.1.1 on 2025-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loanrequest_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='return_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
