# Generated by Django 5.1.1 on 2025-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_loanrequest_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_layer_is_student',
            field=models.BooleanField(default=False),
        ),
    ]
