# Generated by Django 5.1.1 on 2025-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_second_layer_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
