# Generated by Django 5.1.1 on 2025-09-06 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='labs'),
        ),
        migrations.AddField(
            model_name='lab',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
