# Generated by Django 5.1.1 on 2025-09-06 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lab_capacity_lab_image_lab_in_charge_lab_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('from_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='app.lab')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('to_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='app.lab')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
