# Generated by Django 5.1.1 on 2025-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_producttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransfer',
            name='return_product',
            field=models.BooleanField(default=False),
        ),
    ]
